### ISSUE TITLE
[New Feature] 合集 support

### ISSUE THREAD

**Issue by yuioto** [kingwingfly/fav#14]
List subscription 合集 when `fav status -l`.

Want to subscribe to 合集 just like favorites.

Otherwise it will be difficult to download them.

**Comment by kingwingfly** [comment]
Now I have almost finished [`fav_core`](https://crates.io/crates/fav_core).

Mainly 3 traits for `Res`, `ResSet`, `ResSets` ("res" means resource).

But which "合集" did you mean?

This?
<img width="1236" alt="Screenshot 2024-02-18 at 00 15 44" src="https://github.com/kingwingfly/fav/assets/38573173/98468332-8319-462b-8bee-eb17b40cec1f">
Or this?
<img width="1296" alt="Screenshot 2024-02-18 at 00 16 15" src="https://github.com/kingwingfly/fav/assets/38573173/2b31039d-ba3e-4740-ab73-99dd41849bba">

If you mean the latter, it looks like this:
```
[fav_utils_ng/src/bili/ops.rs:72:9] json = Array [
    Object {
        "cid": Number(248053346),
        "dimension": Object {
            "height": Number(1040),
            "rotate": Number(0),
            "width": Number(1920),
        },
        "duration": Number(406),
        "from": String("vupload"),
        "page": Number(1),
        "part": String("1.1 - 简介"),
        "vid": String(""),
        "weblink": String(""),
    },
    Object {
        "cid": Number(248053380),
        "dimension": Object {
            "height": Number(1040),
            "rotate": Number(0),
            "width": Number(1920),
        },
        "duration": Number(198),
        "from": String("vupload"),
        "page": Number(2),
        "part": String("1.2 - 安装 Rust"),
        "vid": String(""),
        "weblink": String(""),
    },
    Object {
        "cid": Number(248053407),
        "dimension": Object {
            "height": Number(1040),
            "rotate": Number(0),
            "width": Number(1920),
        },
        "duration": Number(251),
        "from": String("vupload"),
        "page": Number(3),
        "part": String("1.3 - Hello World"),
        "vid": String(""),
        "weblink": String(""),
    },
...
```
The problem is: Is it a `Res` or `ResSet`? Or I just easily treat it as several `Res`? 

By the way, 合集 is favorited only if one of the videos is favorited. It's not acceptable to save the whole.

However, it can be implemented by defining `Res` like this:
```proto
message BiliRes {
    string bvid = 1;
    string title = 2;
    int32 status = 3;
    int64 cid = 4;
    repeated BiliPage pages = 5;
    Upper owner = 15;
}

message BiliPage {
    int64 cid = 1;
    int32 page = 2;
    string part = 3;
}
```
Use a for loop on pages to download.

**Comment by yuioto** [comment]
合集  has multiple aids or bids. If there are multiple cids in one aid or bid, it should be called 分集.

So, I'm talking about the former.

for example https://www.bilibili.com/festival/bnj2024

**Comment by kingwingfly** [comment]
@yuioto Finished in v0.2.29 . Test it as you like.
